import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {chromium} from 'playwright-core';

const {FASTCAS_CONTRACT_ORIGIN: origin,FASTCAS_CONTRACT_INVITE: invite,FASTCAS_CONTRACT_RECOVERY: recovery} = process.env;
if(!origin||!invite||!recovery)throw Error('browser contract configuration missing');
const browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:390,height:844}});
const page=await context.newPage();
page.setDefaultTimeout(5000);
function totp(uri){
 const secret=new URL(uri).searchParams.get('secret');
 if(!secret)throw Error('TOTP secret missing');
 const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,value=0;const bytes=[];
 for(const letter of secret.replace(/=+$/,'').toUpperCase()){const digit=alphabet.indexOf(letter);if(digit<0)throw Error('invalid TOTP secret');value=(value<<5)|digit;bits+=5;if(bits>=8){bits-=8;bytes.push((value>>bits)&255)}}
 const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));
 const digest=createHmac('sha1',Buffer.from(bytes)).update(counter).digest();const offset=digest[19]&15;
 const number=((digest[offset]&127)<<24)|((digest[offset+1]&255)<<16)|((digest[offset+2]&255)<<8)|(digest[offset+3]&255);
 return String(number%1000000).padStart(6,'0');
}
try{
 await page.goto(`${origin}/console/?flow=invite&token=${encodeURIComponent(invite)}`,{waitUntil:'networkidle'});
 await page.waitForURL(url=>!url.search);
 assert.equal(new URL(page.url()).search,'','invite token remained in URL');
 await page.getByLabel('姓名').fill('Invited Reader');
 await page.getByLabel('新密码',{exact:true}).fill('invited-reader-password-123');
 await page.getByLabel('确认新密码').fill('invited-reader-password-123');
 await page.getByRole('button',{name:'创建 FastCAS 账号'}).click();
 await page.getByRole('status').getByText('账号已创建').waitFor();
 await page.getByRole('link',{name:'前往登录'}).first().click();
 await page.locator('input[name=email]').fill('invited@example.test');
 await page.locator('input[name=password]').fill('invited-reader-password-123');
 await page.getByRole('button',{name:'登录',exact:true}).click();
 await page.getByRole('heading',{name:'你好，Invited Reader'}).waitFor();
 await page.getByLabel('原 FastCAS 密码').fill('invited-reader-password-123');
 await page.getByLabel('新 FastCAS 密码',{exact:true}).fill('invited-reader-changed-456');
 await page.getByLabel('确认 FastCAS 新密码').fill('invited-reader-changed-456');
 await page.getByRole('button',{name:'修改 FastCAS 密码'}).click();
 await page.getByRole('status').getByText('FastCAS 密码已更新').waitFor();
 await page.goto(`${origin}/login`);
 await page.locator('input[name=email]').fill('invited@example.test');
 await page.locator('input[name=password]').fill('invited-reader-password-123');
 await page.getByRole('button',{name:'登录',exact:true}).click();
 assert.match(await page.locator('body').innerText(),/authentication_required/,'old self-service password was accepted');
 await page.goto(`${origin}/login`);
 await page.locator('input[name=email]').fill('invited@example.test');
 await page.locator('input[name=password]').fill('invited-reader-changed-456');
 await page.getByRole('button',{name:'登录',exact:true}).click();
 await page.getByRole('heading',{name:'你好，Invited Reader'}).waitFor();
 await page.getByRole('button',{name:'登录会话'}).click();
 await page.getByRole('heading',{name:'登录会话'}).waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'mobile console overflow');
 await page.getByRole('button',{name:'退出',exact:true}).click();
 await page.getByRole('heading',{name:'登录 FastCAS'}).waitFor();
 await page.goto(`${origin}/console/?flow=recovery&token=${encodeURIComponent(recovery)}`,{waitUntil:'networkidle'});
 await page.waitForURL(url=>!url.search);
 assert.equal(new URL(page.url()).search,'','recovery token remained in URL');
 await page.getByLabel('新密码',{exact:true}).fill('alice-replaced-password-123');
 await page.getByLabel('确认新密码').fill('alice-replaced-password-123');
 await page.getByRole('button',{name:'更新 FastCAS 密码'}).click();
 await page.getByRole('status').getByText('密码已更新').waitFor();
 await page.getByRole('link',{name:'前往登录'}).first().click();
 await page.locator('input[name=email]').fill('alice@example.test');
 await page.locator('input[name=password]').fill('correct horse battery staple');
 await page.getByRole('button',{name:'登录',exact:true}).click();
 const rejection=await page.locator('body').innerText();
 if(!rejection.includes('authentication_required'))throw Error('old password was not rejected');
 await page.goto(`${origin}/login`);
 await page.locator('input[name=email]').fill('alice@example.test');
 await page.locator('input[name=password]').fill('alice-replaced-password-123');
 await page.getByRole('button',{name:'登录',exact:true}).click();
 await page.getByRole('heading',{name:'你好，Alice'}).waitFor();
 await page.getByRole('button',{name:'退出',exact:true}).click();
 await page.getByRole('heading',{name:'登录 FastCAS'}).waitFor();
 await page.goto(`${origin}/login`);
 await page.locator('input[name=email]').fill('admin@example.test');
 await page.locator('input[name=password]').fill('administrator long password');
 await page.getByRole('button',{name:'登录',exact:true}).click();
 await page.getByRole('heading',{name:'你好，Administrator'}).waitFor();
 const unverified=await page.evaluate(()=>fetch('/api/v1/admin/applications',{credentials:'same-origin'}).then(r=>r.status));
 assert.equal(unverified,403,'administrator access succeeded before MFA');
 await page.getByRole('button',{name:'设置认证器'}).click();
 const uri=await page.getByLabel('认证器配置').inputValue();
 await page.getByLabel('动态验证码或恢复码').fill(totp(uri));
 await page.getByRole('button',{name:'确认验证码并开启'}).click();
 await page.getByText('双重验证：已启用').waitFor();
 const originalRecovery=await page.locator('pre').innerText();
 page.once('dialog',dialog=>dialog.accept());
 await page.getByRole('button',{name:'更新恢复码'}).click();
 await page.getByRole('status').getByText('恢复码已更新').waitFor();
 assert.notEqual(await page.locator('pre').innerText(),originalRecovery,'recovery codes did not rotate');
 await page.getByRole('button',{name:'身份管理'}).click();
 await page.getByRole('heading',{name:'身份管理'}).waitFor();
 assert.equal(await page.getByText('zz-user-105@example.test').count(),0,'old identity was visible before pagination');
 await page.getByRole('button',{name:'加载更多身份'}).click();
 await page.getByText('zz-user-105@example.test').waitFor();
 await page.getByRole('button',{name:'审计',exact:true}).click();
 await page.getByRole('heading',{name:'最近审计'}).waitFor();
 assert.equal(await page.getByText('audit-page-001').count(),0,'old audit was visible before pagination');
 await page.getByRole('button',{name:'加载更多审计'}).click();
 await page.getByText('audit-page-001').waitFor();
 const invalidCursor=await page.evaluate(()=>fetch('/api/v1/admin/audit-events?before=invalid',{credentials:'same-origin'}).then(r=>r.status));
 assert.equal(invalidCursor,403,'invalid audit cursor was accepted');
 await page.getByRole('button',{name:'失败投递'}).click();
 await page.getByRole('heading',{name:'失败投递'}).waitFor();
 await page.getByText('browser-contract-dead').waitFor();
 await page.getByRole('button',{name:'查看投递记录'}).click();
 await page.getByText(/第 12 次 · http_error · HTTP 503 · 42 毫秒/).waitFor();
 assert.equal((await page.locator('body').innerText()).includes('never-return-this'),false,'delivery payload leaked to console');
 await page.getByRole('button',{name:'应用管理'}).click();
 await page.getByRole('heading',{name:'登记应用',exact:true}).waitFor();
 await page.getByLabel('应用 ID').fill('browser-contract-app');
 await page.getByLabel('名称',{exact:true}).fill('Browser Contract');
 await page.getByLabel('回调地址（每行一个）').fill('https://app.example.test/callback');
 await page.getByRole('button',{name:'登记应用',exact:true}).click();
 await page.getByLabel('客户端密钥').waitFor();
 const issuedSecret=await page.getByLabel('客户端密钥').inputValue();
 const registered=await page.evaluate(()=>fetch('/api/v1/admin/applications',{credentials:'same-origin'}).then(r=>r.json()));
 assert.ok(registered.some(item=>item.id==='browser-contract-app'),'application was not stored');
 assert.equal(await page.getByText('zz-app-105').count(),0,'old app was visible before pagination');
 await page.getByRole('button',{name:'加载更多应用'}).click();
 await page.getByText('zz-app-105').waitFor();
 assert.deepEqual(await page.evaluate(()=>Object.keys(localStorage)),[],'one-time secret stored in localStorage');
 page.once('dialog',dialog=>dialog.accept());
 await page.locator('article').filter({hasText:'browser-contract-app'}).getByRole('button',{name:'轮换密钥'}).click();
 let rotatedSecret=issuedSecret;
 for(let attempt=0;attempt<100&&rotatedSecret===issuedSecret;attempt++){
  await page.waitForTimeout(50);
  rotatedSecret=await page.getByLabel('客户端密钥').inputValue();
 }
 assert.notEqual(rotatedSecret,issuedSecret,'rotated secret unchanged');
 await page.getByRole('button',{name:'开发者接入'}).click();
 await page.getByRole('heading',{name:'接入顺序'}).waitFor();
 await page.locator('code').filter({hasText:origin}).first().waitFor();
 await page.getByText('browser-contract-app').waitFor();
 assert.equal((await page.locator('body').innerText()).includes(rotatedSecret),false,'client secret leaked to integration guide');
 await page.getByRole('button',{name:'加载更多应用配置'}).click();
 await page.getByText('zz-app-105').waitFor();
 await page.getByRole('button',{name:'服务身份'}).click();
 await page.getByRole('heading',{name:'登记服务身份'}).waitFor();
 await page.getByLabel('服务 ID').fill('browser-contract-service');
 await page.getByLabel('名称',{exact:true}).fill('Browser Contract Service');
 await page.getByLabel('允许的 Scope').fill('insight:publish');
 await page.getByLabel('资源受众').fill('research-api');
 await page.getByRole('button',{name:'登记服务'}).click();
 await page.getByLabel('服务客户端密钥').waitFor();
 const serviceSecret=await page.getByLabel('服务客户端密钥').inputValue();
 assert.ok(serviceSecret.length>20,'service secret missing');
 const services=await page.evaluate(()=>fetch('/api/v1/admin/service-accounts',{credentials:'same-origin'}).then(r=>r.json()));
 assert.ok(services.some(item=>item.client.id==='browser-contract-service'&&item.active),'service account was not stored');
 assert.equal(await page.getByText('zz-service-105').count(),0,'old service was visible before pagination');
 await page.getByRole('button',{name:'加载更多服务身份'}).click();
 await page.getByText('zz-service-105').waitFor();
 assert.deepEqual(await page.evaluate(()=>Object.keys(localStorage)),[],'one-time service secret stored in localStorage');
 page.once('dialog',dialog=>dialog.accept());
 const createdService=page.locator('article').filter({hasText:'browser-contract-service'});
 await createdService.getByRole('button',{name:'停用',exact:true}).click();
 await createdService.getByRole('button',{name:'重新启用'}).waitFor();
 await createdService.getByRole('button',{name:'重新启用'}).click();
 await page.getByLabel('服务客户端密钥').evaluate((element,original)=>{
   if(element.value===original)throw Error('re-enabled service secret unchanged');
 },serviceSecret);
 await page.getByRole('button',{name:'邀请与恢复'}).click();
 await page.getByLabel('目标邮箱').fill('another@example.test');
 await page.getByRole('button',{name:'生成一次性凭证'}).click();
 await page.getByLabel('一次性凭证').waitFor();
 const priorCredential=await page.getByLabel('一次性凭证').inputValue();
 await page.getByLabel('操作').selectOption('mfa_reset');
 await page.getByLabel('目标邮箱').fill('admin@example.test');
 await page.getByRole('button',{name:'生成一次性凭证'}).click();
 await page.waitForFunction(previous=>{const field=document.querySelector('textarea[aria-label="一次性凭证"]');return field instanceof HTMLTextAreaElement&&field.value.length>20&&field.value!==previous},priorCredential);
 const resetCredential=await page.getByLabel('一次性凭证').inputValue();
 assert.ok(resetCredential.length>20,'MFA reset credential missing');
 await page.getByRole('button',{name:'退出',exact:true}).click();
 await page.getByRole('heading',{name:'登录 FastCAS'}).waitFor();
 await page.goto(`${origin}/console/?flow=mfa_reset&token=${encodeURIComponent(resetCredential)}`,{waitUntil:'networkidle'});
 await page.waitForURL(url=>!url.search);
 await page.getByLabel('当前 FastCAS 密码').fill('administrator long password');
 const resetResponsePromise=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/v1/recover-mfa');
 await page.getByRole('button',{name:'重置双重验证'}).click();
 const resetResponse=await resetResponsePromise;
 assert.equal(resetResponse.status(),200,'MFA reset request failed');
 await page.getByRole('status').getByText('双重验证已重置').waitFor();
 await page.getByRole('link',{name:'前往登录'}).first().click();
 await page.locator('input[name=email]').fill('admin@example.test');
 await page.locator('input[name=password]').fill('administrator long password');
 await page.getByRole('button',{name:'登录',exact:true}).click();
 await page.getByText('双重验证：未启用').waitFor();
 const resetAdminAccess=await page.evaluate(()=>fetch('/api/v1/admin/applications',{credentials:'same-origin'}).then(r=>r.status));
 assert.equal(resetAdminAccess,403,'administrator retained management access after MFA reset');
 console.log('FastCAS browser contract passed: invite, login, logout, password and MFA recovery, MFA enrollment and recovery-code rotation, audit pagination, delivery history, developer integration guide, application registration, service lifecycle, secret rotation and invitation');
}catch(error){
 console.error('browser state:',page.url(),(await page.locator('body').innerText().catch(()=>'' )).slice(0,700));
 throw error;
}finally{await browser.close()}
