import React, {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import {Admin} from './Admin';
import {Delegations} from './Delegations';
import {Integration} from './Integration';
import {Guest,takeInitialCredential} from './Guest';
const initialCredential=takeInitialCredential();
type Me={user:{name:string;email:string;role:string};csrf:string;mfa_enabled:boolean;session:{id:string}};
type Link={id:string;client_id:string;local_account_ref:string;state:string;version:number};
type Installation={id:string;client_id:string;client_name:string;installation_id:string;created_at:string;revoked_at:string|null};
type Session={id:string;authenticated_at:string;expires_at:string};
type Event={id:string;client_id:string;attempts:number;last_status:number|null;dead_at:string|null};
type DeliveryAttempt={id:number;attempt:number;outcome:string;http_status:number|null;duration_ms:number;finished_at:string};
function App(){
 const [me,setMe]=useState<Me>();const [page,setPage]=useState('security');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);
 const [password,setPassword]=useState('');const [code,setCode]=useState('');const [uri,setUri]=useState('');const [recovery,setRecovery]=useState<string[]>([]);
 const [currentPassword,setCurrentPassword]=useState('');const [newPassword,setNewPassword]=useState('');const [confirmPassword,setConfirmPassword]=useState('');const [changeCode,setChangeCode]=useState('');
 const [links,setLinks]=useState<Link[]>([]);const [installations,setInstallations]=useState<Installation[]>([]);const [installationCursor,setInstallationCursor]=useState('');const [sessions,setSessions]=useState<Session[]>([]);const [events,setEvents]=useState<Event[]>([]);const [cursor,setCursor]=useState('');const [attempts,setAttempts]=useState<Record<string,DeliveryAttempt[]>>({});
 async function api<T>(path:string,body?:unknown):Promise<T>{const response=await fetch('/api/v1'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':me?.csrf??''},body:body===undefined?undefined:JSON.stringify(body)});if(!response.ok){const problem=await response.json().catch(()=>({}));throw new Error(response.status===401?'请先登录或重新验证身份':problem.message||'操作未完成，请检查权限与身份验证状态')}return response.status===204?undefined:response.json()}
 async function refresh(){setMe(await api<Me>('/me'))}
 useEffect(()=>{refresh().catch(e=>{if(e.message!=='请先登录或重新验证身份')setError(e.message)}).finally(()=>setLoading(false))},[]);
 async function run(work:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await work()}catch(e){setError(e instanceof Error?e.message:'请求失败')}finally{setBusy(false)}}
 async function select(next:string){setPage(next);await run(async()=>{if(next==='links')setLinks(await api<Link[]>('/me/links'));if(next==='installations')await loadInstallations();if(next==='sessions')setSessions(await api<Session[]>('/me/sessions'));if(next==='outbox')await loadEvents()})}
 async function loadInstallations(before=''){const data=await api<{installations:Installation[];next_cursor:string}>('/me/device-installations'+(before?'?before='+encodeURIComponent(before):''));setInstallations(before?old=>[...old,...data.installations]:data.installations);setInstallationCursor(data.next_cursor)}
 async function loadEvents(before=''){const data=await api<{events:Event[];next_cursor:string}>('/admin/outbox'+(before?'?before='+encodeURIComponent(before):''));setEvents(before?old=>[...old,...data.events]:data.events);setCursor(data.next_cursor)}
 return <div className="shell"><header><a className="brand" href="/console/">FastCAS<span>账号与安全</span></a>{me&&<button disabled={busy} onClick={()=>void run(async()=>{await api('/logout',{});setMe(undefined);setNotice('已退出 FastCAS')})}>退出</button>}</header>
 <main><div className="intro"><p className="eyebrow">FAST R&D · IDENTITY</p><h1>{me?`你好，${me.user.name}`:'你的科研账号安全中心'}</h1><p>管理关联身份与登录安全。各项目的本地账号、内容和权限由项目独立管理。</p></div>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
 {loading?<p>正在读取账号…</p>:!me?<Guest initial={initialCredential}/>:<>
 <nav aria-label="账号导航">{[['security','安全设置'],['links','关联项目'],['installations','本机安装'],['delegations','跨项目委托'],['sessions','登录会话'],...(me.user.role==='admin'?[['integration','开发者接入'],['identities','身份管理'],['applications','应用管理'],['services','服务身份'],['exchange-policies','调用策略'],['credentials','邀请与恢复'],['audit','审计'],['outbox','失败投递']]:[])].map(([key,label])=><button key={key} aria-current={page===key?'page':undefined} disabled={busy} onClick={()=>void select(key)}>{label}</button>)}</nav>
 {page==='security'&&<div className="grid"><section><h2>身份验证</h2><p>{me.user.email}</p><p>双重验证：{me.mfa_enabled?'已启用':'未启用'}</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api('/me/reauthenticate',{password,code});setPassword('');setCode('');setNotice('身份已重新验证');await refresh()})}}><label>当前密码<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><label>动态验证码或恢复码<input autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)}/></label><button className="primary" disabled={busy}>重新验证身份</button></form></section>
 <section><h2>双重验证</h2><p>使用认证器生成动态验证码。开启后请妥善保存一次性恢复码。</p>{me.mfa_enabled&&<><p>更新恢复码前，请先用上方表单重新验证密码和动态验证码；旧恢复码会立即失效。</p><button disabled={busy} onClick={()=>{if(window.confirm('生成新的恢复码并使所有旧恢复码失效？'))void run(async()=>{const result=await api<{recovery_codes:string[]}>('/me/mfa/recovery-codes',{});setRecovery(result.recovery_codes);setNotice('恢复码已更新，旧码已失效')})}}>更新恢复码</button></>}{!me.mfa_enabled&&!uri&&<button disabled={busy} onClick={()=>void run(async()=>setUri((await api<{otpauth_uri:string}>('/me/mfa/enroll',{})).otpauth_uri))}>设置认证器</button>}{uri&&<><p>将以下 URI 导入你的认证器。此密钥只应由你保存。</p><textarea aria-label="认证器配置" readOnly value={uri}/><button disabled={busy||!code} onClick={()=>void run(async()=>{const result=await api<{recovery_codes:string[]}>('/me/mfa/confirm',{code});setRecovery(result.recovery_codes);setUri('');setCode('');await refresh()})}>确认验证码并开启</button></>}{recovery.length>0&&<><p>请现在保存恢复码，离开页面后不再显示。</p><pre>{recovery.join('\n')}</pre><button onClick={()=>setRecovery([])}>已保存，隐藏恢复码</button></>}</section>
 <section><h2>修改 FastCAS 密码</h2><p>修改后会退出所有 FastCAS 会话和已关联项目中的 FastCAS 登录。本地项目密码不变。</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{if(newPassword!==confirmPassword)throw new Error('两次输入的新密码不一致');await api('/me/password',{current_password:currentPassword,new_password:newPassword,code:changeCode});setCurrentPassword('');setNewPassword('');setConfirmPassword('');setChangeCode('');setMe(undefined);setNotice('FastCAS 密码已更新，请使用新密码重新登录')})}}><label>原 FastCAS 密码<input type="password" autoComplete="current-password" required value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label><label>新 FastCAS 密码<input type="password" autoComplete="new-password" minLength={12} required value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><label>确认 FastCAS 新密码<input type="password" autoComplete="new-password" required value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label>{me.mfa_enabled&&<label>改密动态验证码或恢复码<input autoComplete="one-time-code" required value={changeCode} onChange={e=>setChangeCode(e.target.value)}/></label>}<button className="primary" disabled={busy}>修改 FastCAS 密码</button></form></section></div>}
 {page==='links'&&<section><h2>关联项目</h2><p>解除认证会终止相应 FastCAS 登录授权，保留项目本地账号与内容。</p>{!links.length&&<p>暂无关联项目。请在项目的账号设置中发起认证。</p>}{links.map(link=><article key={link.id}><div><strong>{link.client_id}</strong><p>{link.local_account_ref} · {link.state}</p></div>{link.state!=='revoked'&&<button disabled={busy} onClick={()=>{if(window.confirm('解除这个项目的 FastCAS 认证？'))void run(async()=>{await api('/me/links/'+encodeURIComponent(link.id)+'/revoke',{version:link.version});setLinks(await api<Link[]>('/me/links'))})}}>解除认证</button>}</article>)}</section>}
 {page==='installations'&&<section><h2>本机安装</h2><p>管理通过设备码关联的本机安装。撤销后，本机下次联网检查会清除 FastCAS 关联；本地任务不受影响。</p>{!installations.length&&<p>暂无已关联安装。</p>}{installations.map(item=><article key={item.id}><div><strong>{item.client_name||item.client_id}</strong><p>安装 ID：{item.installation_id}</p><small>{item.revoked_at?'已撤销 · '+new Date(item.revoked_at).toLocaleString():'关联于 '+new Date(item.created_at).toLocaleString()}</small></div>{!item.revoked_at&&<button disabled={busy} onClick={()=>{if(window.confirm('撤销这个本机安装的 FastCAS 关联？'))void run(async()=>{await api('/me/device-installations/'+encodeURIComponent(item.id)+'/revoke',{});setInstallations(old=>old.map(current=>current.id===item.id?{...current,revoked_at:new Date().toISOString()}:current));setNotice('已撤销安装关联')})}}>撤销关联</button>}</article>)}{installationCursor&&<button disabled={busy} onClick={()=>void run(()=>loadInstallations(installationCursor))}>加载更多安装</button>}</section>}
 {page==='delegations'&&<Delegations api={api} busy={busy} run={run}/>}
 {page==='integration'&&me.user.role==='admin'&&<Integration api={api} busy={busy} run={run}/>}
 {page==='exchange-policies'&&<Delegations api={api} busy={busy} run={run} admin/>}
 {page==='sessions'&&<section><h2>登录会话</h2><p>退出所有 FastCAS 会话将通知已关联项目终止使用 FastCAS 登录的会话；项目本地密码登录不受影响。</p><button disabled={busy} onClick={()=>{if(window.confirm('退出所有 FastCAS 会话？'))void run(async()=>{await api('/me/logout-all',{});setMe(undefined);setSessions([]);setNotice('已退出所有 FastCAS 会话')})}}>退出所有 FastCAS 会话</button>{sessions.map(session=><article key={session.id}><div><strong>{session.id===me.session.id?'当前会话':'其他会话'}</strong><p>登录于 {new Date(session.authenticated_at).toLocaleString()}</p><small>到期于 {new Date(session.expires_at).toLocaleString()}</small></div><button disabled={busy} onClick={()=>void run(async()=>{await api('/me/sessions/'+encodeURIComponent(session.id)+'/revoke',{});if(session.id===me.session.id)setMe(undefined);else setSessions(await api<Session[]>('/me/sessions'))})}>退出会话</button></article>)}</section>}
 {me.user.role==='admin'&&['identities','applications','services','credentials','audit'].includes(page)&&<Admin page={page} api={api} busy={busy} run={run}/>}
 {page==='outbox'&&<section><h2>失败投递</h2><p>需要管理员近期双重验证。请先修复接收方故障，再重新排队。投递记录只显示状态与耗时，不显示消息内容。</p>{!events.length&&<p>当前列表为空。</p>}{events.map(event=><article key={event.id}><div><strong>{event.client_id}</strong><p>{event.id}</p><small>已尝试 {event.attempts} 次 · HTTP {event.last_status??'未知'}</small><div><button disabled={busy} onClick={()=>void run(async()=>{const result=await api<{attempts:DeliveryAttempt[]}>('/admin/outbox/'+encodeURIComponent(event.id)+'/attempts');setAttempts(old=>({...old,[event.id]:result.attempts}))})}>查看投递记录</button>{attempts[event.id]&&<ul>{attempts[event.id].map(attempt=><li key={attempt.id}>第 {attempt.attempt} 次 · {attempt.outcome} · HTTP {attempt.http_status??'未收到'} · {attempt.duration_ms} 毫秒 · {new Date(attempt.finished_at).toLocaleString()}</li>)}</ul>}</div></div>{event.dead_at&&<button disabled={busy} onClick={()=>void run(async()=>{await api('/admin/outbox/'+encodeURIComponent(event.id)+'/retry',{});await loadEvents();setNotice('已重新排队')})}>重试投递</button>}</article>)}{cursor&&<button disabled={busy} onClick={()=>void run(()=>loadEvents(cursor))}>加载更多</button>}</section>}
 </>}</main><footer>FastCAS · 可选认证，独立账号</footer></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
